stages:
  - build

variables:
  REGISTRY: $CI_REGISTRY
  IMAGE_NAME: $CI_REGISTRY_IMAGE
  DOCKER_HOST: tcp://docker:2376
  DOCKER_TLS_CERTDIR: "/certs"

build-and-push-image:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - docker build \
        --build-arg GIT_COMMIT=$(echo $CI_COMMIT_SHORT_SHA) \
        --build-arg BUILD_DATE=$(date -u +'%Y-%m-%dT%H:%M:%SZ') \
        --build-arg BUILDKIT_INLINE_CACHE=1 --cache-from $CI_REGISTRY_IMAGE:latest \
        -f ./Dockerfile \
        -t $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG \
        -t $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA \
        .
    - docker tag $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA $IMAGE_NAME:$CI_COMMIT_SHORT_SHA
    - docker tag $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA $IMAGE_NAME:${CI_COMMIT_TAG#v}
    - docker tag $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA $IMAGE_NAME:latest
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA
    - docker push $CI_REGISTRY_IMAGE:${CI_COMMIT_TAG#v}
    - docker push $CI_REGISTRY_IMAGE:latest
  only:
    refs:
      - master
      - main
    variables:
      - $CI_COMMIT_TAG =~ /^v\d+\.\d+\.\d+$/