services:
  db-production:
    container_name: eam-db-production
    profiles: [production]
    image: postgres:latest
    environment:
      POSTGRES_USER: elizielx
      POSTGRES_PASSWORD: elizielx
      POSTGRES_DB: eam
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - eam-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U elizielx"]
      interval: 10s
      timeout: 5s
      retries: 5
  db-development:
    container_name: eam-db-development
    profiles: [development, local]
    image: postgres:latest
    environment:
      POSTGRES_USER: elizielx
      POSTGRES_PASSWORD: elizielx
      POSTGRES_DB: eam
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - eam-network
  api-local:
    container_name: eam-api-local
    profiles: [local]
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - GIT_COMMIT=$(git rev-parse --short=8 HEAD)
        - BUILD_DATE=$(date -u +'%Y-%m-%dT%H:%M:%SZ')
    image: eam-api-local:latest
    env_file:
      - .env
    ports:
      - "3000:3000"
    depends_on:
      - db-development
    networks:
      - eam-network
    restart: unless-stopped
  api:
    container_name: eam-api-production
    profiles: [production]
    image: ghcr.io/yehezkieldio/eam-api:latest
    # image: registry.gitlab.com/yehezkieldio/eam-api:latest
    env_file:
      - .env
    ports:
      - "3000:3000"
    depends_on:
      db-production:
        condition: service_healthy
    networks:
      - eam-network
    restart: unless-stopped
  caddy-production:
    container_name: eam-caddy-production
    profiles: [production]
    image: caddy:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - eam-network
    depends_on:
      - api
    restart: unless-stopped

volumes:
  postgres_data:
    name: eam-postgres-data
  caddy_data:
    name: eam-caddy-data
  caddy_config:
    name: eam-caddy-config

networks:
  eam-network:
    name: eam-network
    driver: bridge