name: Continuous Integration

on:
  push:
    tags:
      - "v*.*.*"
    branches:
      - master
      - main
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push-image:
    name: Build and Publish Docker image
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v') && (github.ref_name == 'master' || github.ref_name == 'main')
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Get short SHA
        id: sha
        run: echo "short=$(git rev-parse --short=8 HEAD)" >> $GITHUB_OUTPUT

      - name: Get version tag
        id: version
        run: |
          VERSION=$(echo $GITHUB_REF | cut -d '/' -f 3)
          TAG_FRIENDLY=$(echo $VERSION | sed 's/^v//')
          echo "version=$TAG_FRIENDLY" >> $GITHUB_OUTPUT

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Extract metadata (tags, labels)
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          file: ./Dockerfile
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ steps.sha.outputs.short }}
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ steps.version.outputs.version }}
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=registry,ref=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
          cache-to: type=inline
          build-args: |
            GIT_COMMIT=${{ steps.sha.outputs.short }}
            BUILD_DATE=$(date -u +'%Y-%m-%dT%H:%M:%SZ')